export const mockedItems = [
  {
    id: 1,
    image: '',
    title: 'Product 1',
    category: 'Category 1',
    description: 'Description 1',
    price: 25,
    quantity: 2,
  },
  {
    id: 2,
    image: '',
    title: 'Product 2',
    category: 'Category 2',
    description: 'Description 2',
    price: 30,
    quantity: 3,
  },
  {
    id: 3,
    image: '',
    title: 'Product 3',
    category: 'Category 3',
    description: 'Description 3',
    price: 35,
    quantity: 1,
  },
  {
    id: 4,
    image: '',
    title: 'Product 4',
    category: 'Category 4',
    description: 'Description 4',
    price: 40,
    quantity: 5,
  },
  {
    id: 5,
    image: '',
    title: 'Product 5',
    category: 'Category 5',
    description: 'Description 5',
    price: 45,
    quantity: 2,
  },
  {
    id: 6,
    image: '',
    title: 'Product 6',
    category: 'Category 6',
    description: 'Description 6',
    price: 50,
    quantity: 1,
  },
  {
    id: 7,
    image: '',
    title: 'Product 7',
    category: 'Category 7',
    description: 'Description 7',
    price: 55,
    quantity: 1,
  },
  {
    id: 8,
    image: '',
    title: 'Product 8',
    category: 'Category 8',
    description: 'Description 8',
    price: 60,
    quantity: 2,
  },
  {
    id: 9,
    image: '',
    title: 'Product 9',
    category: 'Category 9',
    description: 'Description 9',
    price: 65,
    quantity: 4,
  },
  {
    id: 10,
    image: '',
    title: 'Product 10',
    category: 'Category 10',
    description: 'Description 10',
    price: 70,
    quantity: 6,
  },
  {
    id: 11,
    image: '',
    title: 'Product 11',
    category: 'Category 11',
    description: 'Description 11',
    price: 75,
    quantity: 2,
  },
  {
    id: 12,
    image: '',
    title: 'Product 12',
    category: 'Category 12',
    description: 'Description 12',
    price: 80,
    quantity: 2,
  },
  {
    id: 13,
    image: '',
    title: 'Product 13',
    category: 'Category 13',
    description: 'Description 13',
    price: 85,
    quantity: 3,
  },
  {
    id: 14,
    image: '',
    title: 'Product 14',
    category: 'Category 14',
    description: 'Description 14',
    price: 90,
    quantity: 3,
  },
  {
    id: 15,
    image: '',
    title: 'Product 15',
    category: 'Category 15',
    description: 'Description 15',
    price: 95,
    quantity: 1,
  },
  {
    id: 16,
    image: '',
    title: 'Product 16',
    category: 'Category 16',
    description: 'Description 16',
    price: 100,
    quantity: 5,
  },
];
